// <auto-generated />
namespace MvcCatalog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Adicionado_Campo_Imagem_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adicionado_Campo_Imagem_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201410251753406_Adicionado_Campo_Imagem_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
